docs(hook):Add documentation and example of Access Hooks
dynaconf/dynaconf pull request #1160
Opened 2024-07-10 15:57 UTC by rochacbruno

fix #1095

## Template substitutions

Dynaconf has 2 tokens to enable string substitutions, the interpolation works with `@format` and `@jinja`.

### @format token

Dynaconf allows template substitutions for strings values, by using the `@format` token prefix and including placeholders accepted by Python's `str.format` method Dynaconf will call
it lazily upon access time.

The call will be like:

```py
"<YOURVALUE>".format(env=os.environ, this=dynaconf.settings)
```

So in your string you can refer to environment variables via `env` object, and also to variables defined int the settings object itself via `this` reference. It is lazily evaluated on access it will use the final value for a settings regardless the order of load.

Example:

```bash
export PROGRAM_NAME=calculator
```

settings.toml

```toml
[default]
DB_NAME = "mydb.db"

[development]
DB_PATH = "@format {env[HOME]}/{this.current_env}/{env[PROGRAM_NAME]}/{this.DB_NAME}"
```

- `{env[HOME]}` is the same as `os.environ["HOME"]` or `$HOME` in the shell.
- `{this.current_env}` is the same as `settings.current_env`
- `{env[PROGRAM_NAME]}` is the same as `os.environ["PROGRAM_NAME"]` or `$PROGRAM_NAME` in the shell.
- `{this.DB_NAME}` is the same as `settings.DB_NAME` or `settings["DB_NAME"]`

so in your `program`

```py
from dynaconf import settings

settings.DB_PATH == '~/DEVELOPMENT/calculator/mydb.db'
```

`@format` token can be used together with tokens like `@str`, `@int`, `@float`, `@bool`, and `@json` to cast the results parsed by `@format`.

Example: 

Casting to integer from `@format` templated values

```yaml
NUM_GPUS: 4
# This returns the integer after parsing
FOO_INT: "@int @format {this.NUM_GPUS}"
# This returns the string after parsing
FOO_STR: "@format {this.NUM_GPUS}"
```

### @jinja token

If `jinja2` package is installed then dynaconf will also allow the use jinja to render string values.

Example:

```bash
export PROGRAM_NAME=calculator
```

settings.toml

```toml
[default]
DB_NAME = "mydb.db"

[development]
DB_PATH = "@jinja {{env.HOME}}/{{this.current_env | lower}}/{{env['PROGRAM_NAME']}}/{{this.DB_NAME}}"
```

so in your `program`

```py
from dynaconf import settings

settings.DB_PATH == '~/development/calculator/mydb.db'
```

The main difference is that Jinja allows some Python expressions to be evaluated such as `{% for, if, while %}` and also supports calling methods and has lots of filters like `| lower`.

Jinja supports its built-in filters listed in [Builtin Filters Page](http://jinja.palletsprojects.com/en/master/templates/#builtin-filters) and Dynaconf includes additional filters for `os.path` module: `abspath`. `realpath`, `relpath`, `basename` and `dirname` and usage is like: `VALUE = "@jinja {{this.FOO | abspath}}"`

`@jinja` token can be used together with tokens like `@str`, `@int`, `@float`, `@bool`, and `@json` to cast the results parsed by `@jinja`.

Example:

Casting to integer from `@jinja` templated values

```yaml
NUM_GPUS: 4
# This returns the integer after parsing
FOO_INT: "@int @jinja {{ this.NUM_GPUS }}"
# This returns the string after parsing
FOO_STR: "@jinja {{ this.NUM_GPUS }}"
```

Example:

Casting to a `json` dict from `@jinja` templated values

```yaml
MODEL_1:
  MODEL_PATH: "src.main.models.CNNModel"
  GPU_COUNT: 4
  OPTIMIZER_KWARGS:
    learning_rate: 0.002

MODEL_2:
  MODEL_PATH: "src.main.models.VGGModel"
  GPU_COUNT: 2
  OPTIMIZER_KWARGS:
    learning_rate: 0.001

# Flag to choose which model to use
MODEL_TYPE: "MODEL_2"

# This returns the dict loaded from the resulting json
MODEL_SETTINGS_DICT: "@json @jinja {{ this|attr(this.MODEL_TYPE) }}"

# This returns the raw json string
MODEL_SETTINGS_STR: "@jinja {{ this|attr(this.MODEL_TYPE) }}"
```

## Name aliasing

In certain cases you need to reuse some variable value respecting the exact 
data type it is previously defined in another step of the settings load.

Example:

```py title="config.py"
from dynaconf import Dynaconf
settings = Dynaconf(settings_files=["settings.toml", "other.toml"])  
```

```toml title="settings.toml"
thing = "value"
number = 42
```

```toml title="other.toml"
other_thing = "@get thing"

# providing default if thing is undefined
other_thing = "@get thing 'default value'"

## type casting
# Ensure the aliased value is of type int
other_number = "@get number @int"

# Ensure type and provide default if number is undefined
other_number = "@get number @int 12"
```

The `@get` is lazily evaluated and subject to `DynaconfFormatError` in case of
malformed expression, it is recommended to add validators.

## Access Hooks

Dynaconf can be configured to retrieve a special variable from an external
storage such as GCP or AWS secrets or a Vault server or even a secret located
on the filesystem or encrypted.

This feature is useful to load settings from BitWarden and other secret managers.

NOTES:
   - You must define the logic of each hook, dynaconf just calls it
   - You must take care of caching and caching invalidation

```python
# So you have a function that retrieves data from external source

CACHE = {}  # could be Redis

def get_data_from_somewhere(settings, result, key, *args, **kwargs):
    """Your function that goes to external service like gcp, aws, vault, etc"""
    # result.value is 'special:/foo/bar:token'
    if key in CACHE:
        return CACHE[key]

    if isinstance(result.value, str) and result.value.startswith("@special:"):
        _, path, key = result.value.split(":")
        # value = get_value_from_special_place(path, key)
        value = CACHE[key] = "lets believe it was retrieved from special place"
        return value

    return result

# ---

from dynaconf import Dynaconf
from dynaconf.hooking import HookableSettings, Hook, Action

# Create a Dynaconf instance
settings = Dynaconf(
    # set the Hookable wrapper class
    _wrapper_class=HookableSettings,
    # Register your hooks, you can have AFTER_GET, BEFORE_GET
    # you can have multiple hooks, value passes from one to another
    _registered_hooks={
       Action.AFTER_GET: [Hook(get_data_from_somewhere)]
    },
)

# this value can actually come from settings files or envvars
settings.set("token", "@special:/vault/path:token")

assert settings.token == "lets believe it was retrieved from special place"

# from cache this time
assert settings.token == "lets believe it was retrieved from special place"
```

2024-07-13 21:08 UTC, sebastian-correa requested changes
Thanks for adding this to the docs! I think it's a welcome feature and letting people know about it is always a bonus. Are there any plans about the "privacy" of the hooks attribute? The leading `_` might look daunting to some users.

Not sure what to say about the changes done to `app.py`. Should I just run `make test_functional` and be happy if there are no complains?

BTW, I'd say the only blocking request is the one about the list not rendering properly.

2024-07-13 21:08 UTC, sebastian-correa commented on docs/dynamic.md
> +to wrap the result value and process the merging before returning.
Non-blocking: I think this is more explicit, though it's non-blocking because I think the example is quite self explanatory.

```suggestion
and you want the merging to be applied, then the hook must delegate the merging
to the given `settings` by `set`ing the result (which will perform the merging)
and returning the result of `get`ing the setting from the given `settings`.
```

2024-07-13 21:09 UTC, sebastian-correa commented
Argh, sorry I reviewed this when @pedro-psb was assigned, I didnt' even notice! My bad! :S

2024-07-14 10:52 UTC, rochacbruno commented
Thanks @sebastian-correa I addressed your suggestions

2024-07-14 10:59 UTC, rochacbruno commented
@sebastian-correa 

> Are there any plans about the "privacy" of the hooks attribute? The leading _ might look daunting to some users.

It was necessary to avoid conflict for example of a user has a setting variable names `wrapped_class`.

With the new schema on 4.0.0 I think we can make it better by adding the hook individually on each Annotated key.

```py
class Settings(Dynaconf):
    token: Annotated[str, AccessHook(my_function)]
```


> Not sure what to say about the changes done to app.py. Should I just run make test_functional and be happy if there are no complains?

That is just a test that runs on CI, if you run `make tests_functional` or `./tests_functional/runtests.py --filter hooking` it must run and pass the test.

2024-07-14 15:48 UTC, sebastian-correa approved these changes
🚀

Thanks for addressing all of my comments and making this new doc section!

2024-07-14 19:00 UTC, merged