[WiP]docs(pt-br): Docs Translation to brazilian portugues.
dynaconf/dynaconf pull request #787
Opened 2022-08-11 15:13 UTC by Riverfount

This is a first version in PT-BR of Dynaconf Documentation.
At the moment was translated index.md and cli.md

2022-08-11 20:07 UTC, jonatasoli requested changes

2022-08-11 20:07 UTC, jonatasoli commented on docs/pt-br/docs/index.md
> +???+ "Usando somento Python"
```suggestion
???+ "Usando somente Python"
```

2022-08-11 20:07 UTC, jonatasoli commented on docs/pt-br/docs/index.md
> +    #### Usando somento Python
```suggestion
    #### Usando somente Python
```

2022-08-11 20:07 UTC, jonatasoli commented on docs/pt-br/docs/index.md
> +    ├── config.py       # Where you import your settings object (required)
```suggestion
    ├── config.py       # Aonde você importa seu objeto de configuração  (obrigatório)
```

2022-08-11 20:07 UTC, jonatasoli commented on docs/pt-br/docs/index.md
> +    ├── .secrets.toml   # Sensitive data like passwords and tokens (optional)
```suggestion
    ├── .secrets.toml   # Arquivos com dados sensíveis como senhas e tokens (opcional)
```

2022-08-11 20:07 UTC, jonatasoli commented on docs/pt-br/docs/index.md
> +    └── settings.toml   # Application setttings (optional)
```suggestion
    └── settings.toml   # Configuração da Aplicação (opcional)
```

2022-08-29 19:27 UTC, Riverfount commented on docs/pt-br/docs/cli.md
> +  --banner             Mostra um baner maneiro
I fixed the errors pointed out.

2022-08-29 19:27 UTC, Riverfount commented on docs/pt-br/docs/cli.md
> +  -i, --instance TEXT  Define a instância custumizada do LazySettings
I fixed the errors pointed out.

2022-08-29 19:27 UTC, Riverfount commented on docs/pt-br/docs/cli.md
> +  list      Litas todos os valores de configuração definidos pelo usuário se `--all` é passado ...
I fixed the errors pointed out.

2022-08-29 19:27 UTC, Riverfount commented on docs/pt-br/docs/index.md
> +    └── settings.toml   # Application setttings (optional)
I fixed the errors pointed out.

2022-08-29 19:28 UTC, Riverfount commented on docs/pt-br/docs/cli.md
> +Todo comando (com exceção do init) requer uma Instância que pode ser passada usano o parâmetro `-i` ou por variável de ambiente com `export INSTANCE_FOR_DYNACONF`
I fixed the errors pointed out.

2022-08-29 19:28 UTC, Riverfount commented on docs/pt-br/docs/index.md
> +???+ "Usando somento Python"
I fixed the errors pointed out.

2022-08-29 19:28 UTC, Riverfount commented on docs/pt-br/docs/index.md
> +    ├── config.py       # Where you import your settings object (required)
I fixed the errors pointed out.

2022-08-29 19:28 UTC, Riverfount commented on docs/pt-br/docs/index.md
> +    ├── .secrets.toml   # Sensitive data like passwords and tokens (optional)
I fixed the errors pointed out.

2022-08-29 19:33 UTC, jonatasoli approved these changes
![image](https://i.etsystatic.com/12431793/r/il/8356a9/1910533733/il_794xN.1910533733_hfkn.jpg)

2022-08-29 19:45 UTC, jonatasoli commented
I think change Draft status this PR.

2022-09-02 17:30 UTC, rochacbruno approved these changes

2022-09-02 19:28 UTC, merged