Improve
dynaconf/dynaconf pull request #989
Opened 2023-08-25 19:17 UTC by sebastian-correa

# Summary
Fixes #911 and #968 by adding documentation on some `Dynaconf` parameters and reworking the `Validation` section of the docs.

# Details
Not much detail to give, as context is present in the 2 linked issues.

Aside from the obvious additions to `configuration.md` and `validation.md`, I updated the Pyhon version in `CONTRIBUTING.md` to 3.8+ and added `.DS_Store` file to `.gitignore`. In particular, any of these 2 unrelated changes could be dropped from this PR if needed :).

# Questions
1. Links between Markdown files don't seem to work on my local docs (`make docs`). Did I do something wrong or do they get fixed when deployed to the web?

# Notes
Please feel free to ask _any_ changes in this PR. The idea is to improve Dynaconf.

2023-08-25 19:22 UTC, sebastian-correa commented
Maybe I have to do absolute links (without the `./` at the start?

2023-08-28 17:54 UTC, pedro-psb requested changes
This is looking way better. I'm opinionated on some small things, but feel free to disagree if you have different motivations. And as I've said before, the grammar/type checker is better than me on catching typos, so I didn't bother with this too much.

2023-08-28 17:54 UTC, pedro-psb commented on docs/validation.md
> -<h4>Trigger manually</h4>
I think this information about keys is good, but it might be a best fit as first thing on the Usage section (along with some general info about a Validator object). 

---

... (overview)

# Usage

To define validation rules, you must create `Validator` objects, which are constructed using *keys* (positional arguments) and *rules* (kwargs):

```python
Validator("AGE", gte=20, lte=80) # multiple rules
Validator("NAME", "VERSION", "PORT", must_exist=True) # multiple keys
Validator("DB.PORT", eq=8080) # keys with dot-path notation
```

There are some different ways to use them, as we'll see.

... (on instatiation)

2023-08-28 17:54 UTC, pedro-psb commented on docs/validation.md
> +#### On instantiation
I would make this example way smaller to just illustrate what a Validation exception looks like and the default behavior on instantiation (will gather all errors, not just the first). The full example could be moved/linked down to References.

I think it overwhelming to have complex examples on initial sections and, for those who need them (may already know the basics), it's easy to go with links or the ToC.

2023-08-28 17:54 UTC, pedro-psb commented on docs/validation.md
> +### With CLI
This section could have a learn-more-link to `/cli#dynaconf-validate`.

2023-08-28 17:54 UTC, pedro-psb commented on docs/validation.md
> +#### Static default values
I would suppress all feature sub-headers from ToC (but not the text). In my opinion, it is more readable to have a flat listing, and it doesn't hide any vital information.

```diff
    Multiple Validators
    Custom messages
    Default values
-        Static default values
-        Computed default values
    Casting / Transform
    Custom conditional expressions
    Conditional Validation
    Combination Operators
-        or operator (|)
-        and operator (&)
    Selective Validation
    Validating only the current_env
```

2023-08-28 17:54 UTC, pedro-psb commented on docs/validation.md
> +The `condition` argument expects a `Callable` that receives the setting's value as its only argument and returns a `bool`ean value.
"and returns a `bool`."

2023-09-04 01:45 UTC, sebastian-correa commented on docs/validation.md
> +#### On instantiation
I agree. I made the example smaller. I'm not sure the current "full" example adds anything beyond this smaller one, so I've dropped it for now. We can always recover it if you feel we should keep it (let me know!).

2023-09-04 01:47 UTC, sebastian-correa commented on docs/validation.md
> -<h4>Trigger manually</h4>
Done. What's the go-to section that explains that Dynaconf can handle weird keys? Like dotted lookups, the difference between upper and lower case, keys with `__`, and such? Maybe we should link it here.

2023-09-04 01:56 UTC, sebastian-correa commented on docs/configuration.md
My bad about the typos. Went through them with a VSCode spell-checking extension.

2023-09-04 01:57 UTC, sebastian-correa commented
Thanks @pedro-psb for your input and patience. I pushed some changes, you can look at the diff [here](https://github.com/dynaconf/dynaconf/compare/8a6a3ce6cc204d85704cfaec9ad9f8837e00d5d1..22b02488da801f34c7373131cb917f4bca9fbbe3).

Please don't hesitate to re-ask for changes, and please mark as solved any discussions you think should be closed.

2023-09-04 16:34 UTC, pedro-psb commented on docs/validation.md
> -<h4>Trigger manually</h4>
I'm not sure there if there is a single place where this is presented.

2023-09-04 17:18 UTC, pedro-psb requested changes
I think this is good after the link fix. You can check if it works by running the mkdocs local server or in the Netlify comment (there is a link to a live preview of the PR).

2023-09-04 17:18 UTC, pedro-psb commented on docs/configuration.md
> +Read more about it in the [selective validation](./validation#selective-validation) section.
This dot causes the link to resolve as `configuration/validation#selective-validation`, causing it to break.
We should have a link health checker in the dev tool chain.

2023-09-04 17:18 UTC, pedro-psb commented on docs/configuration.md
> +In practice, this forwards `validate_only` to the `only` kwarg during the validation step upon `Dynaconf` instantiation for all `Validator`s passed. Note that this setting has interaction with [`vali
Here `#validation-exclude` should be `#validation_exclude`, because it uses `_` explicitly. The link should use `-` when it comes from a whitespace transformation (e.g, if it was `validation exclude`).

2023-09-04 17:18 UTC, pedro-psb commented on docs/validation.md
> +You can override this globally with the option [validate_on_update](/configuration/#validate-on-update) or
Same here, the original uses literal underscores. I didn't see this detail about dash-underscore on my previous review.

2023-09-06 12:30 UTC, sebastian-correa commented
Hey @pedro-psb, I'll look at your comments during the weekend. My bad with the links though, I could've sworn that I went through all of them :S.

2023-09-10 18:51 UTC, sebastian-correa commented
@pedro-psb sorry this is taking so long, I don't have much time mid-week to tackle this PR :S. I've now re-read and it looks like its better now. I'll look check all links from the dev deploy once it's ready.

2023-09-11 18:03 UTC, pedro-psb approved these changes
@sebastian-correa Don't need to apologize, I'm glad you took the effort to contribute!
It's good to go, we'll ship it in 3.2.4

2023-09-15 18:51 UTC, merged